### PR TITLE
Draft: Proposal for 'H'-extension ordering

### PR DESCRIPTION
**Pull request by a4lg**
Related: #837
PDF file (Chapter 28 only): https://github.com/a4lg/riscv-isa-manual/releases/tag/a4lg%2Fsnapshots%2F2022-04-23%2Fnaming-ext-ordering-pvnh.3

I hope this helps understanding outline of my proposal.

### CODE REVIEW

**Comment by aswaterman** [comment]
The N extension doesn’t belong in this list, and it’s off-topic for this PR, anyway. Please remove it.

**Comment by a4lg** [comment]
I updated the draft pull request.

**Comment by aswaterman** [comment]
Thanks!

**Comment by a4lg** [comment]
Still, let me explain why I applied #831 first.

On #837, I outlined extension category ordering as follows (excerpt):

| Software / Spec           | Related Ext. Ordering     | Notes |
| ------------------------- | ------------------------- | ----- |
| 4. GNU Binutils           | (K… →) P → V → N      | |
| 5. GCC                    | (K… →) P → V → N      | |
| 6. LLVM (single-letter)   | P → V → N               | |
| RISC-V ISA 20191213       | P → V → N               | `H` is missing |

Many software already implements P → V → N order.  It's hard to remove N on most cases.

| Software / Spec           | Related Ext. Ordering     | Notes |
| ------------------------- | ------------------------- | ----- |
| 3. QEMU (Past)            | P → V → N… → H        | |
| 6. LLVM (`Z*` extensions) | P → V → N… → H → K   | `K` must be fixed (out of scope from this issue) |

P → V → N → H order is implemented in QEMU (Past) and almost compatible to LLVM (in development) `Z*` extensions.  So, I felt P → V → N → H ordering is more natural (than P → V → H (→ N)) and I wanted to show that fact explicitly.

Still, your concerns are completely valid.

**Comment by aswaterman** [comment]
Yeah, I'm not concerned about how tools are ordering N, given that there is no such thing as N formally.  But I do appreciate that you provided this information; it helps with reasoning about the H situation.

**Comment by aswaterman** [comment]
Manually merged.

**Pull request closed without merging**
