### PR TITLE
Separate transformation for HLV instructions

### PR DESCRIPTION
**Pull request by jhauser-us**

### CODE REVIEW

**Comment by aswaterman** [comment]
Just confirming that the intent here just to distinguish the fact that HLV has a funct5 field in place of HSV's rs2.

**Comment by pdonahue-ventana** [comment]
Doesn't the definition of HLV/HLVX in section 8.3.1 still contain the rs2 field instead of funct5?

**Comment by jhauser-us** [comment]
Paul Donahue wrote:
> Doesn't the definition of HLV/HLVX in section 8.3.1 still contain the rs2 field instead of funct5?

Good point.

Andrew, given that the encodings of a few other instructions (CSR and FCVT) are also shown as using the rs2 field to encode something other than a register operand, should we just back out of this commit entirely?  It's in response to a public comment that bits 24:20 were labeled "rs2" when they aren't actually a register for HLV/HLVX.  Yet there's precedent that field "rs2" isn't always a register.

**Comment by aswaterman** [comment]
Agreed.  Reverted via 714c50aa294e0c56a2d5adc3b7559a6f200b3044.  If we ever decide to revisit this topic throughout the ISA, we should revisit this, too.

**Pull request merged**
