### PR TITLE
add docs-resources submodule to get pdf theme,fonts, and global attri…

### PR DESCRIPTION
**Pull request by kbroch-rivosinc**
…butes

related to #1448

### CODE REVIEW

**Comment by wmat** [comment]
The github action is failing to find the docs-resources. Perhaps the include path needs adjustment. I'd do it but I'm on my phone atm.

**Comment by kbroch-rivosinc** [comment]
> The github action is failing to find the docs-resources. Perhaps the include path needs adjustment. I'd do it but I'm on my phone atm.

yes, The docker build is working fine locally but  I'm not appreciating some difference in the GH actions and paths.
I'm going to try to simplfy the make script and align it more with what's in docs-spec-template (without changing any of the build targets/outputs)

**Review by wmat — APPROVED** [review]
LGTM.  Thanks for this.

**Comment by aswaterman** [comment]
@wmat @kbroch-rivosinc This should not have been merged as-is.  The build system is now less functional than it used to be.  In particular, dependence tracking no longer works properly.

We shouldn't be forcing consistency with other repos just for consistency's sake.  There really isn't a good reason this repo looks identical to the other ones; it has a different set of concerns and constraints than one-off repos for new extensions.

I will fix the problems that have been re-introduced, but going forward, please involve me when you make significant changes to stuff I've been working on.

**Pull request merged**
