### PR TITLE
Add PAUSE hint

### LINKED ISSUE #43: Guidance requested: instruction for spin-wait loops
Linux is presently using `div a5,a5,zero` for `cpu_relax` (actually the register is variable but it winds up being `a5` in 80% of sites); glibc and Go currently generate no instructions for `atomic_spin_nop` and `runtime.procyield`.

### PR DESCRIPTION
**Pull request by aswaterman**
Closes #43

### CODE REVIEW

**Comment by aswaterman** [comment]
I’m probably just rehashing the discussion we already had, but: I don’t think there’s much benefit from distinguishing the two, as the processor can just unstall when either event (IO or memory) occurs, and there’s likely no loss in efficiency in practice. In fact, given the likelihood of misuse, it might perform better this way around ;)

I would view the predecessor field as just another opcode field when the successor field is zero. It doesn’t really matter if the bits line up with their usual purpose, as they are feeding into different control logic (or so I claim without proof).

I’m not outright opposed to the change, but I need a stronger argument to change my mind.

**Comment by palmer-dabbelt** [comment]
Can we just talk in person when I'm back next week?  I'm running out of
email writing energy... 😁

**Comment by aswaterman** [comment]
Sure.

**Comment by aswaterman** [comment]
@gfavor this is rebased and ready for merging whenever we deem appropriate.

**Comment by knightsifive** [comment]
Minor suggestion: perhaps the enhancements to the HINT discussion could be separated from the addition of the PAUSE discussion. (I suggest this only because there has been some contention about PAUSE on the mailing lists.)

**Comment by David-Horner** [comment]
Perhaps you saw Krste response on google ISA list

https://groups.google.com/a/groups.riscv.org/g/isa-dev/c/0VUZAEl6o0g/m/KCYUUMZTCQAJ.

This revision to HINT is distinct from an enhanced version of PAUSE.

There was also extensive discussion on [RISC-V] [tech] Start of 45-day 
public review period for "PAUSE Hint instruction" extension.

The enhancement discussion will most likely always occur.

What the process has demonstrated this time is that clarifications and 
cleanups of proposals are incorporated,
even if design enhancements with fundamentally substantial changes are not.



On Wed, Dec 16, 2020, 16:38 Nick Knight, <notifications@github.com 
<mailto:notifications@github.com>> wrote:

    Minor suggestion: perhaps the enhancements to the HINT discussion
    could be separated from the addition of the PAUSE discussion. (I
    suggest this only because there has been some contention about PAUSE
    on the mailing lists.)

    —
    You are receiving this because you are subscribed to this thread.
    Reply to this email directly, view it on GitHub
    <https://github.com/riscv/riscv-isa-manual/pull/398#issuecomment-747056570>,
    or unsubscribe

**Comment by aswaterman** [comment]
@knightsifive If the PAUSE discussion drags on, I'll separate these into PRs.  I kept them together because redoing LaTeX these tables is time-consuming, and the changes are coupled.

**Pull request merged**
