### PR TITLE
Unprivileged ISA - colophon and preamble section review

### PR DESCRIPTION
**Pull request by ved-rivos**
riscv-isa-unpriv.adoc - added missing newline
colophon.adoc
 - Added missing entries to first table
 - Bolded section header
 - Bolded "Ratified" term to match table

### CODE REVIEW

**Review by aswaterman — CHANGES_REQUESTED** [review]
This PR changes 148 files.  Surely that is not the intent of a review of the colophon and preamble?

**Comment by ved-rivos** [comment]
Only two files were updated . Let me check the PR again for sanity - hope
it did not create one against master instead of covert2adoc branch

Ved

**Comment by aswaterman** [comment]
Ah, that is the issue.  The PR was made against master.

**Comment by ved-rivos** [comment]
This should be the PR - https://github.com/riscv/riscv-isa-manual/pull/749
Hope this works.
ved

**Comment by aswaterman** [comment]
OK, closing this one.  Thanks.

**Comment by elisa-riscv** [comment]
Yes, it looks like you had created a PR against Master and not the convert
branch.

**Comment by ved-rivos** [comment]
On 10/4/21 5:51 PM, Elisa Sawyer wrote:
> Yes, it looks like you had created a PR against Master and not the convert
> branch.
> 
Sorry about that :( I sent an updated PR - hope that worked.

regards
ved

**Pull request closed without merging**
