### PR TITLE
Fix typo in FENCE diagram

### PR DESCRIPTION
**Pull request by zakkak**
As discussed in
https://groups.google.com/a/groups.riscv.org/forum/#!topic/sw-dev/iiXF1PXvwrM

### CODE REVIEW

**Comment by aswaterman** [comment]
This change makes the figure spill into the margins.  I'll just fix the comment to say "instruction bits 31:28" instead.

**Comment by sorear** [comment]
Can we also update the "Instruction listing" to show the ignored fields of FENCE and FENCE.I as actually-ignored rather than must-be-zero?

**Comment by aswaterman** [comment]
Any suggestions as to how that should be presented?

**Comment by sorear** [comment]
Might be enough to include rs1/rd in the table (like in [1.0](https://www2.eecs.berkeley.edu/Pubs/TechRpts/2011/EECS-2011-62.pdf#page=31), oddly), and let people refer to the long description.

**Pull request closed without merging**
