### PR TITLE
Add PMM field to *envcfg and mseccfg

### PR DESCRIPTION
**Pull request by aswaterman**
cc @martinmaas

### CODE REVIEW

**Comment by jhauser-us** [comment]
I thought the Architecture Review Committee wanted the name of the field to be PMM (Pointer Masking Mode), not PME.

**Comment by gfavor** [comment]
That's what I seem to remember as well.

Greg

**Comment by aswaterman** [comment]
Thanks for the correction.  I'll take this as approval modulo that change, so I'll merge shortly.

**Comment by aswaterman** [comment]
@martinmaas please also update the pointer-masking spec to reflect the name PMM rather than PME.

**Comment by martinmaas** [comment]
This is now updated in the pointer masking spec as well:

https://github.com/riscv/riscv-j-extension/commit/d6f29a61e5a5a834d048250e0e92690d0cde9e04

**Comment by aswaterman** [comment]
Thank you!

**Pull request merged**
