### PR TITLE
Don't conflate hart and system

### PR DESCRIPTION
**Pull request by pdonahue-ventana**
Heterogeneous systems can have different privilege mode support in different harts, can have different XLEN support in different harts, etc.

### CODE REVIEW

**Review by aswaterman — APPROVED** [review]

**Comment by aswaterman** [comment]
Please rebase and fix conflicts (and ping me again if needed), then I'll merge.

**Comment by pdonahue-ventana** [comment]
@aswaterman: My fork was in some ancient state when I started, causing all kinds of trouble for me.  I think that this is now ready to go.

**Review by aswaterman — APPROVED** [review]

**Comment by aswaterman** [comment]
Thanks.

**Comment by andreiw** [comment]
This change seems to have accidentally reverted https://github.com/riscv/riscv-isa-manual/commit/f44e4fa741bed0d3aacb994b564e3ad594db5df9 @gfavor

**Pull request merged**
