### PR TITLE
Clarify pseudoinstruction sign extension neglected

### PR DESCRIPTION
**Pull request by diekmann**
As discussed in issue 144, the table "RISC-V pseudoinstructions" in the
placeholder "RISC-V Assembly Programmer's Handbook" chapter neglects
sign extension for brevity. This commit adds this assumption explicitly
to the table.

I was lying on the beach (no Internet, no laptop), reading a printout of the RISC V manual. Nice read, thanks! But I spent a long time staring at the pseudoinstruction table and reading the parts about sign extension again and again, because I thought my understanding of sign extension was wrong. I was so desperate that left the beach to find a computer. Fortunately, @andrewt0301 already raised the same question in issue #144. Though the whole assembly programming chapter will be replaced, please accept this little commit to make the risc v manual a better reading material for the upcoming holiday season :smile:

### CODE REVIEW

**Comment by diekmann** [comment]
Ping @aswaterman

**Comment by aswaterman** [comment]
What do you think about actually fixing the table, rather than adding the caveat?  It's just a matter of adding bit 11 into the high part.

For example, for la,

    _Let delta = symbol - pc_
    auipc rd, delta[31:12] + delta[11]
    addi rd, rd, delta[11:0]

**Comment by diekmann** [comment]
Sure! To avoid further round trips, fell free to make this change yourself. Otherwise, I will modify this pull request *soon*™.

**Comment by aswaterman** [comment]
I can wait ;)

**Comment by diekmann** [comment]
Updated (via force push) as discussed. I split content-related changes and typesetting-only into separate commits.

Did I get `call offset` and `tail offset` right?

This is how the improved typesetting looks like: imgur

**Comment by aswaterman** [comment]
OK, I took this with slight tweaks in 3f05dd6

**Comment by diekmann** [comment]
:+1: :+1: :+1: 

Yep, your wording is nicer.

Nit-picking: Your explanation uses passive voice. It is not specified which magical entity actually subtracts and adds the bits. Using active voice instead, we could clarify that the compiler does this.

But the current version is absolutely fine and everything is understandable from the context.

**Comment by aswaterman** [comment]
I chose to use the passive voice to be deliberately vague (because it's not the compiler, it's the linker).  If you want to change it to active voice with linker as the subject, that's fine with me, too.

**Pull request closed without merging**
