### PR TITLE
Integrated Ssqosid extension

### PR DESCRIPTION
**Pull request by ved-rivos**

### CODE REVIEW

**Review by aswaterman — APPROVED** [review]
I quickly scanned the spec and didn't see other cases where we included in the mainline text the priv version number that added a feature.  I'll strip that from this text and instead add a changelog entry.

I'll also fix a typo (there is a stray `55`).

**Comment by aswaterman** [comment]
Manually merged via 6114bf9a1312f6b9309b32a138ef04c0754eac09

**Comment by ved-rivos** [comment]
Thanks!

**Comment by ved-rivos** [comment]
@aswaterman - "The P1P13 bit in mstateen0 controls access to the hedelegh introduced by Privileged Specification Version
1.13." Was this the text you intended to add to change log? If so it is still in there.

**Comment by aswaterman** [comment]
I created a new changelog with only one entry for P1P14.  (I didn't change the changelog for the ratified spec, which includes the P1P13 entry.)

**Pull request closed without merging**
