### PR TITLE
Name change to represent Processor

### PR DESCRIPTION
**Pull request by stineje**
Request name change to Wally as that is the real name of the process and may be confused with the name originally created during the PR of CVW.  Thank you for helping!

### CODE REVIEW

**Review by aswaterman — CHANGES_REQUESTED** [review]
The PR title and description don't match the contents.  The contents are purely additive, whereas the description suggests a change to existing contents.  Can you update the description and title to match the contents?

**Comment by kersten1** [comment]
@stineje is this change still needed? If so, please make the requested changes. If not, please close the PR.

**Comment by kersten1** [comment]
@stineje Any update? If not, I'll close this PR in 2 weeks (week of May 28th)

**Comment by stineje** [comment]
Apologies - my fault.  Yes, we would like to change to reflect the name of our project.  The OpenHW link is there.  I will be happy to fix, if needed.  Sorry, once again - it is my fault.

**Comment by aswaterman** [comment]
No prob.  I resolved the merge conflict and merged it.

**Comment by stineje** [comment]
Many thanks Andrew - so sorry for all the issues.

**Comment by aswaterman** [comment]
You're welcome!

**Pull request merged**
