### PR TITLE
Make it explicit that the page-fault exceptions from address translation correspond to the original access type, as is done for access exceptions.

### PR DESCRIPTION
**Pull request by pmundkur**
It is implicit, but being more explicit seemed better.

### CODE REVIEW

**Comment by aswaterman** [comment]
What do you think about making this change for the first sentence only?  It is pretty verbose.

**Comment by pmundkur** [comment]
On 15:39 Wed 21 Mar, Andrew Waterman wrote:
> What do you think about making this change for the first sentence only?  It is pretty verbose.

Sure.  It would be good to make the treatment consistent for access
exceptions and page-faults.  Perhaps a single line about both before
the enumerated steps, and omit the qualifications inside the
enumerated steps?

**Comment by aswaterman** [comment]
Yeah, let’s see how that looks. Thanks!

**Comment by pmundkur** [comment]
@aswaterman  any opinion on how it looks?

**Comment by aswaterman** [comment]
After comparing them, I prefer your first version :) I've merged it.  Thanks.

**Pull request closed without merging**
