### PR TITLE
Attempts to access non-existent CSRs are reserved

### LINKED ISSUE #1116: Accessing an unimplemented CSR is reserved, not necessarily illegal
The old clause was incorrect, as sometimes a virtual instruction exception must be raised instead.

(It's also inconsistent with the rest of RISC-V, which recommends but does not mandate exceptions for reserved encodings.  And, furthermore, the existence of non-conforming extensions made the old mandate toothless: an implementation could purport to have a non-conforming extension at every otherwise-unused CSR address.)

### PR DESCRIPTION
**Pull request by aswaterman**
Resolves #1116

### CODE REVIEW

**Comment by allenjbaum** [comment]
If there is an attempt to access a non-existent CSR (or write a
non-existent CSR in the Read-only region) - is there no guarantee even then
that it will get an illegal instruction exception?
Or, it is guaranteed only for implemented CSRs at an insufficient priv
level? (i.e. which has higher priority, insufficient priv or unimplemented)?

I would vote for insufficient priv level here.....

**Comment by aswaterman** [comment]
Unimplemented CSRs don’t have a defined privilege level, so they can’t trap on the basis of privilege (The use of bits 9:8 for privilege is just a convention, as is the use of bits 11:10 for writability.)

**Comment by allenjbaum** [comment]
Hmm; given the description of the regions in the spec, I thought of it as
far more than a convention, but more like a ... spec.

**Comment by aswaterman** [comment]
The title of the section that describes the encoding uses the word "conventions"...

**Comment by pdonahue-ventana** [comment]
Notably, the ratified debug 0.13 spec did not follow that convention.  The mscontext CSR in debug 1.0 continues to not follow that convention but it's now deprecated and replaced by something that follows the convention.

**Review by gfavor — APPROVED** [review]
LGTM.

**Comment by jrtc27** [comment]
Both BBL and OpenSBI probe CSR existence by whether they trap, e.g. for PMP registers (but more extensive in OpenSBI). Does this loosening of the spec not break that such that now _conforming_ implementations don't have to trap on accessing those CSRs if they don't implement them, whereas previously it was only non-conforming implementations, due to the CSRs being in the standard encoding space?

**Comment by aswaterman** [comment]
In effect, they are requiring something along the lines of Ssstrict (or Smstrict, really, which hasn't been defined).  That may well be the right thing for them to do, but the assumption should be codified.

**Comment by jrtc27** [comment]
If we're going to add things then we might as well just spell out in the hardware description, as we do for something like the Zicbo* cache block sizes, how many registers there are (or whatever else OpenSBI probes for, which may just be giving extension names to things). But at the moment we're in a bit of a dodgy spot where the spec relaxed something that was relied upon, but there's nothing in its place listed as a requirement by those implementations.

**Comment by jrtc27** [comment]
Cc @atishp04 @avpatel as OpenSBI and platform-y people

**Pull request merged**
