### PR TITLE
Fix wording and formatting of x0 special cases

### PR DESCRIPTION
**Pull request by pfusik**
Restore semicolons removed accidentally in aaad788afe0019ebb5c63d3c3193e9d951c3f3e0

### CODE REVIEW

**Comment by wmat** [comment]
Thanks for this, those semicolons somehow went missing.  Can I suggest that you also change the "only valid" to "valid only", as it's grammatically an improvement.

**Comment by pfusik** [comment]
How about normalizing these "not equal" signs? Some are UTF-8, some are HTML entities and some are latexmath. I think UTF-8 would be best.

**Comment by wmat** [comment]
I think UTF-8 would work.  Perhaps add attributes to the header docs for UTF-8 replacements, such as:

:le: &#8804;
:ge: &#8805;
:lt: &#60;
:gt: &#62;

Then replace in the asciidoc files with attribute references such as {ge}

**Comment by pfusik** [comment]
What do you mean by "header docs" ? Why use attribute references if we can (and already do) directly use Unicode characters? Especially for ASCII characters such as `<` and `>`.

**Comment by wmat** [comment]
Asciidoc requires header docs, for the ISA manuals, they are riscv-unprivileged.adoc and riscv-privileged.adoc.  At the beginning of each is a set of attributes that asciidoctor requires to build the full documents.  Adding attributes for unicode would but down on a few keystrokes for extension authors.

**Comment by pfusik** [comment]
I see, there's no `≠` on keyboards. But it was already extensively used and WYSIWYG. It's easier to copy the whole phrase than to re-type it. `latexmath` ended up in HTML as SVG - not good for screen readers.

**Comment by pfusik** [comment]
When merging, please select my Samsung email.

**Review by aswaterman — CHANGES_REQUESTED** [review]
The title of this PR does not reflect what it actually does.  It makes several wording changes.

**Review by aswaterman — APPROVED** [review]
Much improved, thank you.

**Pull request merged**
