### PR TITLE
Improve readability of sentence

### PR DESCRIPTION
**Pull request by muks**
I've updated the wording so it's clearer. Please let me know if you prefer something else.

### CODE REVIEW

**Comment by aswaterman** [comment]
I don’t agree that this improves readability.

**Comment by muks** [comment]
Without the "in this way" qualification, it reads as:

>  "immediates ... have been allocated to reduce hardware complexity."

instead of

>  "immediates ... have been allocated in this way to reduce hardware complexity."

.. the "in this way" referring to "generally packed towards the leftmost available bits."

Please do consider a colleague's opinion. I created this PR because it was not readable to me.

**Comment by aswaterman** [comment]
Packing the immediates to the left does not reduce hardware complexity. The sentence means the right thing as written.

**Comment by muks** [comment]
The correct meaning is "immediates reduce hardware complexity" ? In that case I have misread it.

**Pull request closed without merging**
