### PR TITLE
Intel tossed TSX

### PR DESCRIPTION
**Pull request by palmer-dabbelt**
Signed-off-by: Palmer Dabbelt <palmer@rivosinc.com>

### CODE REVIEW

**Review by aswaterman — CHANGES_REQUESTED** [review]
Is this not premature given https://en.wikipedia.org/wiki/Sapphire_Rapids?

If the final nail in the TSX coffin does come, we should probably instead write something like the following, to preserve the historical note and avoid "why not use TM?" questions:

"As x86 has dropped support for transactional memory, a move away from DW-CAS appears unlikely."

**Comment by solomatnikov** [comment]
TSX is not the only implementation of transactional memory.

**Comment by apinski-cavium** [comment]
ARM defines theirs here: https://developer.arm.com/documentation/ddi0617/latest
But I don't think any HW is actually going to implement it ...

**Comment by gfavor** [comment]
Having come from the ARM world, ARM developed their TM extension a fair
number of years ago and I'm not aware of any designs implementing it after
all these years - including ARM designs.

Greg

**Comment by allenjbaum** [comment]
IBM still has transactional memory, as far as I know.
 I've always wondered what magic they have that let them avoid the pitfalls
everyone else seems to have run into.

**Comment by apinski-cavium** [comment]
> IBM still has transactional memory, as far as I know. I've always wondered what magic they have that let them avoid the pitfalls everyone else seems to have run into.

IBM removed it in Power10.

**Comment by brouhaha** [comment]
Despite removing it from POWER10, IBM does still has transactional memory. It's in z/Architecture, and was introduced in the Tenth Edition of IBM z/Architecture Principles of Operation, dated September 2012, and first implemented in zEC12 systems announced on August 28, 2012. The 14th edition of the PoO dated May 2022 still includes it, and AFAICT the current z16 generation "Telum" microprocessor still supports it.
It seems premature to declare hardware transactional memory dead, even if it is pretty tricky to get it right. I still would like to see a hardware transaction memory specification for RISC-V. "We choose to define RISC-V hardware transactional memory in this decade and do the other things, not because they are easy, but because they are hard"

**Comment by strikerdw** [comment]
Smiles... as someone with the scar tissue on this one, I laughed a bit at
"even if it is pretty tricky to get it right"... smiles, that doesn't even
begin to cover the pain involved :-).

Especially if your write footprint has ambitions of being large than 8-16
cachelines.

I will say that if you ever do get seriously drunk and try to do TM, do
NOT, repeat NOT, put a suspend mode in it. EVER.

As to the Kennedy quote and the Apollo program, we have nowhere near the
amassed resources that took and possibly not the massed resources this will
take..... It really is ugly and hard. Be sure you want to do this to
yourselves.

Going back to the original email... it has been years since I've looked at
the Intel specs on this, but is TSX the magic thing where they tried to
elide locks and replace critical sections automatically with TM? If so, is
it just that part of TM that Intel is tossing or is it the whole kit and
kaboodle including the explicitly manually coded transactions as well?

Derek Williams

**Comment by brouhaha** [comment]
Intel TSX originally consisted of hardware lock elision (HLE) and restricted transactional memory (RTM).  HLE has been thrown under the bus, but it appears that Intel is still committed (no pun intended) to RTM.

**Comment by strikerdw** [comment]
Fair enough. Thanks for the clarification.

Derek Williams

**Comment by guoren83** [comment]
> Intel TSX originally consisted of hardware lock elision (HLE) and restricted transactional memory (RTM). HLE has been thrown under the bus, but it appears that Intel is still committed (no pun intended) to RTM.

I also hope riscv could keep Intel TSX RTM style and define "xstart/xend/xabort/xtest" is not a big budget for the ISA. For multi-cache lines atomic synchronization, TSX is the best solution for current. The traditional aligned atomic semantics (including DCAS) are limited to one cacheline.

**Comment by kersten1** [comment]
Found this one in the ASCIIDOC so I'm deleting this PR as completed elsewhere.

**Pull request closed without merging**
