### PR TITLE
Proposal to explicitly declare things as UNSPECIFIED

### PR DESCRIPTION
**Pull request by pdonahue-ventana**
Here are my proposed changes in support of https://github.com/riscv/riscv-isa-manual/issues/377.

Note that many more things would presumably fall into this UNSPECIFIED category but this pull request contains the basic definition and a few concrete examples.  Documenting other behaviors and values as UNSPECIFIED can be done later as necessary.

### CODE REVIEW

**Comment by pdonahue-ventana** [comment]
Any thoughts or feedback on this?  Thanks.

**Comment by aswaterman** [comment]
I agree with the sentiment, but I think a finer categorization might be appropriate.  For example, the Alpha spec distinguishes UNPREDICTABLE from UNDEFINED.  Their UNDEFINED is similar in some respects to your UNSPECIFIED, whereas their UNPREDICTABLE is very constrained (namely, only registers the instruction could ordinarily write are written, and memory isn't accessible to the current protection domain isn't accessed).   ARMv8 uses the term UNPREDICTABLE in a similar way as Alpha.

The remark about reserved opcodes is addressed to some extent by this paragraph: https://github.com/riscv/riscv-isa-manual/blob/master/src/intro.tex#L706

**Comment by pdonahue-ventana** [comment]
> I agree with the sentiment, but I think a finer categorization might be appropriate. For example, the Alpha spec distinguishes UNPREDICTABLE from UNDEFINED. Their UNDEFINED is similar in some respects to your UNSPECIFIED, whereas their UNPREDICTABLE is very constrained (namely, only registers the instruction could ordinarily write are written, and memory isn't accessible to the current protection domain isn't accessed). ARMv8 uses the term UNPREDICTABLE in a similar way as Alpha.

I would be very happy with a finer categorization and my original inclination was to go with an Alpha-like approach (having worked on Alpha long ago).  By the time I wrote this proposal, I had decided to simplify to more closely approximate what I believe to be the current state of RISC-V where there aren't really any constraints.  In doing so, I hoped that it would be less controversial.

I believe that there ideally ought to be constraints that prevent security holes.  My current thinking is that those constraints belong in the privileged architecture (as part of the further constraint that UNSPECIFIED allows extensions to do) rather than in the unprivileged architecture since I think that an implementation that doesn't include the privileged architecture has no security and so can't have any security holes.  Perhaps hangs should be mentioned in the unprivileged architecture, though.

While UNSPECIFIED can more closely mirror UNPREDICTABLE (whether in the presence of the privileged architecture or not), I'm not sure there's a need for something like the UNDEFINED behavior of Alpha and MIPS.  ARM and Power don't seem to have such a notion, at least not explicitly.

> The remark about reserved opcodes is addressed to some extent by this paragraph: https://github.com/riscv/riscv-isa-manual/blob/master/src/intro.tex#L706 -- I guess I'm also worried about people reading "undefined opcodes are have unspecified behavior" as "these architects have no idea what they're doing," when in actuality, platform specifications are expected to nail down this behavior precisely.

In reality, undefined opcodes do have unspecified and completely unbounded behavior in the base architecture.  I think that it's better to say this explicitly rather than having half of the people assume (as I did initially) that reserved opcodes must trap since that's how "everyone else" does it and the other half (who come from more of a microcontroller background) maybe assuming something else.  Perhaps your concern would be addressed with additional non-normative text that says that platforms are expected to describe the behavior.  Overall, I think that having the rigor of UNSPECIFIED makes it less likely that people believe that the architects don't know what they're doing and non-normative text can further help bolster confidence in the architects.

The few uses of UNSPECIFIED I included were just some examples for illustrative purposes.  My main goal is to advocate for everything being fully described either precisely or using UNSPECIFIED.  If my reserved instruction verbiage is blocking things then I'd rather pull that out for a separate discussion at a later time and focus now on whether UNSPECIFIED is a good idea in general and what constraints it should have (such as security holes and hangs).

**Comment by aswaterman** [comment]
Thanks for the additional insight, Paul.

I agree that what concretely constitutes a security hole belongs in the privileged architecture, but feel that the unprivileged architecture should still state that UNSPECIFIED behavior mustn't open security holes, in the abstract sense.

My current thinking is that everything that's UNSPECIFIED in the unprivileged architecture could instead be said to be PLATFORM-SPECIFIED.  The definition of the two terms might not be any different at this level, as ultimately, a given platform may leave the behavior relatively unconstrained.  But I think the alternate terminology better indicates the intent that the behavior be specified--just specified elsewhere.  Any thoughts on that?

**Comment by pdonahue-ventana** [comment]
My understanding of the current state of affairs is that there is this hierarchy:
1. base architecture
2. extensions
3. platform standard*
4. implementation

Each level can constrain anything that is not specified by the levels above.  That's generally similar to what you seem to be saying but you have fewer levels.

I tried to capture this in the pull request:
> Extensions, platform standards, or implementation documentation may
> provide normative content to further constrain cases that the base
> architecture defines as \unspecified.

and:
> Like the base architecture, extensions should fully describe allowable
> behavior and values and use the term \unspecified\ for cases that are
> intentionally unconstrained.  These cases may be constrained or defined
> by other extensions, platform standards, or implementations.

However, the term PLATFORM-SPECIFIED implies:
1. extensions cannot constrain the behavior of things not specified in the base architecture
2. platforms such as the Unix platform can be expected to constrain all such behaviors

For those reasons, I believe that this term isn't quite right.  I'm open to other terms but cannot think of one that is as descriptive as UNSPECIFIED.

As for prohibiting security holes in all cases, I'm completely in favor of such restrictions.

** I believe that there may be some confusion about the dual use of the word "platform" in RISC-V to mean both:
1. a standard, such as the Unix platform, with which implementations may comply and
2. any such hardware implementations themselves, as defined in section 1.1 of the base architecture.

**Pull request merged**
