### PR TITLE
Run root Docker as the current user

### PR DESCRIPTION
**Pull request by Timmmm**
Reapplication of 3539eff338352aba83dbae9e7b310d6a7d9a7d56 but this time we only add the `--user` argument for root Docker. Rootless Docker behaves the same as Podman and doesn't need the `--user` flag; in fact it breaks builds if you add it.

I also added a comment for the `:z` flag.

### CODE REVIEW

**Comment by Timmmm** [comment]
IMO a better solution than messing around with Docker/Podman is Apptainer, which is explicitly designed for this use case and takes care of exposing mounts etc. for you. Unfortunately people are unlikely to have it installed already so we're probably in an "everyone uses shitty Bash scripts because Bash is already there" sort of situation. :-/

**Comment by aswaterman** [comment]
FWIW, this version works on my Mac.

**Comment by wmat** [comment]
The Release new ISA When merging a PR still fails.  I recognize why this is happening.  We'll try to figure out how to fix this.

**Comment by Timmmm** [comment]
It won't pass because it's running from my fork.

If you run it manually for `master` it should work though. I think the configuration needs to be changed a bit, I'm not a GitHub actions pro though....

**Comment by wmat** [comment]
I fixed up the workflow and it's working as it should now.

**Pull request merged**
