### PR TITLE
Polish the assembly example to avoid potential confusion

### PR DESCRIPTION
**Pull request by DehengYang**

### CODE REVIEW

**Review by aswaterman — CHANGES_REQUESTED** [review]
I'll let @daniellustig decide what to do here.  This still isn't legal RISC-V assembly (since the result of `sc.w` needs to be written somewhere), and it has introduced a new bug: the figure caption assumes all of the `sc` instructions are labeled `(c)`.

**Comment by DehengYang** [comment]
Sorry for my mistake. I noticed that the `(c)`  appears only once in the Figure caption and is not used in other places of the context:

> Figure A.4: In all four (independent) code snippets, the store-conditional (c) is permitted but not
guaranteed to succeed

What if we change it to:

>  Figure A.4: In all four (independent) code snippets, the store-conditional (sc.w) is permitted but not
guaranteed to succeed

Please kindly advise. Thank you!

**Comment by aswaterman** [comment]
Some of the snippets use `sc.d`, not `sc.w`, so that isn't quite right either.  How about:

Figure A.4: In all four (independent) code snippets, the final store-conditional instruction is permitted but not guaranteed to succeed

And then to fix the other issue, change all of the `sc` instructions to write a result to `t3`, e.g. `sc.w t3, t2, 0(s0)` in this case.  If Dan approves of that version, we can merge it.

**Comment by DehengYang** [comment]
That looks great! Thank you very much for the advice, which makes the manual more rigorous, sound, and easily understandable.

**Comment by daniellustig** [comment]
Thanks for the PR @DehengYang.  One more quick comment: shouldn't we still pair `lr.w` with `sc.w`, and `lr.d` with `sc.d`?  The first two snippets now pair `lr.d` with `sc.w`.

**Comment by DehengYang** [comment]
@daniellustig Thank you very much for the comment. I have fixed it for your consideration.

**Review by aswaterman — APPROVED** [review]

**Comment by aswaterman** [comment]
Thanks, y'all!

**Pull request merged**
